- hosts: localhost
  gather_facts: False

  tasks:
    - name: Provision a set of instances
      ec2:
        assign_public_ip: true
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        count: 1
        group_id: "{{ security_id }}"
        image: "{{ ami_id }}"
        #instance_profile_name
        instance_tags:
          Name: Demo
          owner: "{{ owner }}"
          randomizer: "{{ randomizer }}"
        instance_type: "{{ instance_type }}"
        key_name: "{{ key_name }}"
        region: "{{ region_name }}"
        state: present
        #user_data
        #volumes
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        wait: true
        #zone
      register: ec2

    - name: Add all instance public IPs to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groups: ec2hosts
      loop: "{{ ec2.instances }}"

    # shows the json data for the instances created
    - name: Show ec2 instance json data
      debug:
        msg: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_ip }}"
        port: 22
        delay: 60
        timeout: 600
        state: started
      loop: "{{ ec2.instances }}"

    - name: remove ssh fingerprints
      known_hosts:
        name: "{{ item.public_ip }}"
        state: absent
      loop: "{{ ec2.instances }}"

    - name: Accept new ssh fingerprints
      local_action: shell ssh-keyscan -H "{{ item.public_ip }}" >> ~/.ssh/known_hosts
      loop: "{{ ec2.instances }}"

- hosts: ec2hosts
  user: ec2-user
  gather_facts: False

  tasks:
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
      become: yes
